staging_url: "http://keisuke-funatsu.sakura.ne.jp/staging"

staging_title: "WordPress　demo site staging"

staging_plugins:
  - show-current-template

production_url: "http://keisuke-funatsu.sakura.ne.jp/production"

production_title: "WordPress　demo site production"

production_plugins:
  - all-in-one-seo-pack
  - google-sitemap-generator
  - walti

common_plugins:
  - all-in-one-wp-security-and-firewall
  - contact-form-7
  - flamingo
  - cf7-invisible-recaptcha
  - tinymce-advanced
  - wp-mail-smtp
  - wp-multibyte-patch
  - wp-total-hacks
  - broken-link-checker
  - wordpress-importer
  - all-in-one-wp-migration
