sakura_rental_server:
  hosts:
    default_server:
      ansible_host: "{{ lookup('env', 'SAKURA_HOST_NAME') }}"
      ansible_user: "{{ lookup('env', 'SAKURA_USER_NAME') }}"
      ansible_ssh_pass: "{{ lookup('env', 'SAKURA_SSH_PASS') }}"
      # pythonのsshモジュールを指定
      ansible_connection: paramiko
  vars:
    ansible_python_interpreter: /usr/local/bin/python
