sakura_rental_server:
  hosts:
    default_server:
      ansible_host: "{{ sakura_host_name }}"
      ansible_user: "{{ sakura_user_name }}"
      ansible_ssh_pass: "{{ sakura_ssh_pass }}"
      # pythonのsshモジュールを指定
      ansible_connection: paramiko
  vars:
    ansible_python_interpreter: /usr/local/bin/python
