- name: Install backup.sh
  template:
    src: backup.sh.j2
    dest: ~/bin/backup.sh

- name: Set cron
  cron:
    name: "Backup WordPress"
    hour: "{{ cron_hour }}"
    minute: "{{ cron_minute }}"
    state: "{{ 'present' if cron_enable else 'absent' }}"
    job: ~/bin/backup.sh
