- name: Create tmp directory
  file:
    path: ~/tmp
    state: directory

- name: Download WordPress test data
  get_url:
    url: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml
    dest: ~/tmp/wordpress_test_data.xml

- name: Install WordPress importer plugin to import test data
  command: "wp plugin install wordpress-importer --activate"
  args:
    chdir: "~/www/{{ working_directory }}"

- name: Import WordPress test data
  command: "wp import ~/tmp/wordpress_test_data.xml --authors=create"
  args:
    chdir: "~/www/{{ working_directory }}"

- name: Delete test data
  file:
    path: ~/tmp/wordpress_test_data.xml
    state: absent
