- name: tmpディレクトリを作成
  file:
    path: ~/tmp
    state: directory

- name: WordPressのテストデータをダウンロード
  get_url:
    url: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml
    dest: ~/tmp/wordpress_test_data.xml

- name: テストデータ導入のためにWordPress importer プラグインを導入する
  command: "wp plugin install wordpress-importer --activate"
  args:
    chdir: "~/www/{{ item.directory }}"

- name: WordPress test dataをインポートする
  command: "wp import ~/tmp/wordpress_test_data.xml --authors=create"
  args:
    chdir: "~/www/{{ item.directory }}"

- name: ダウンロードしたテストデータを削除する
  file:
    path: ~/tmp/wordpress_test_data.xml
    state: absent
