- name: どの環境を作成するか表示
  debug:
    msg: "{{ item.setting_name }}を作成します"

- name: 環境毎にディレクトリを作成する
  file:
    path: "~/www/{{ item.directory }}"
    state: directory

- name: WordPress日本語版をダウンロードする
  command: "wp core download --locale=ja"
  args:
    chdir: "~/www/{{ item.directory }}"
    creates: index.php

- name: wp-config.phpを作成する
  command: |
    wp config create
    --dbname={{ item.db_name }}
    --dbuser={{ sakura_user_name }}
    --dbpass={{ sakura_db_password }}
    --dbhost={{ sakura_db_host }}
    --dbprefix={{ item.db_prefix | default('wp_') }}
    --extra-php="{{ item.extra_php }}"
  args:
    chdir: "~/www/{{ item.directory }}"
    creates: wp-config.php

- name: WordPressをインストールする
  command: |
    wp core install
    --url='{{ item.site_url }}'
    --title='{{ item.site_title }}'
    --admin_user='{{ item.admin_user_name }}'
    --admin_password='{{ item.admin_password }}'
    --admin_email='{{ item.admin_mail }}'
  args:
    chdir: "~/www/{{ item.directory }}"

- name: プラグインをインストールする
  include_tasks: plugins.yml
  vars:
    working_directory: "{{ item.directory }}"
    plugins: "{{ item.plugins }}"

- name: パーマリンク構造を変更
  command: wp rewrite structure '/%postname%/'
  args:
    chdir: "~/www/{{ item.directory }}"

- name: パーマリンク設定を更新する
  command: wp rewrite flush
  args:
    chdir: "~/www/{{ item.directory }}"
