- name: Create staging directory
  file:
    path: "~/www/{{ staging_directory }}"
    state: directory

- name: Download WordPress to stating environment
  command: "wp core download --locale=ja"
  args:
    chdir: "~/www/{{ staging_directory }}"
    creates: index.php

- name: Set up wp-config.php for stating environment
  command: |
    wp config create
    --dbname={{ staging_db_name }}
    --dbuser={{ sakura_db_user }}
    --dbpass={{ sakura_db_pass }}
    --dbhost={{ sakura_db_host }}
    --extra-php="define( 'WP_DEBUG', true );
    define( 'WP_DEBUG_LOG', true );
    define('DISALLOW_FILE_EDIT',true);"
  args:
    chdir: "~/www/{{ staging_directory }}"
    creates: wp-config.php

- name: Install WordPress on stating environment
  command:
    wp core install
    --url='{{staging_url}}'
    --title='{{staging_title}}'
    --admin_user='{{ staging_admin_name }}'
    --admin_password='{{ staging_admin_pass }}'
    --admin_email='{{ staging_admin_mail }}'
  args:
    chdir: "~/www/{{ staging_directory }}"

- name: Install common plugins on staging environment
  command: "wp plugin install {{ item }} --activate"
  args:
    chdir: "~/www/{{ staging_directory }}"
  with_items: "{{ common_plugins }}"

- name: Install staging plugins on staging environment
  command: "wp plugin install {{ item }} --activate"
  args:
    chdir: "~/www/{{ staging_directory }}"
  with_items: "{{ staging_plugins }}"

- name: Rewrite permalink structure
  command: "wp rewrite flush"
  args:
    chdir: "~/www/{{ staging_directory }}"
