- name: Create staging directory
  file:
    path: "{{ lookup('env', 'STAGING_DIRECTORY') }}"
    state: directory

- name: Download WordPress to stating environment
  command: "wp core download --locale=ja"
  args:
    chdir: "{{ lookup('env', 'STAGING_DIRECTORY') }}"
    creates: index.php

- name: Set up wp-config.php to stating environment
  command: |
    wp config create --dbname={{ lookup('env', 'STAGING_DB_NAME') }} --dbuser={{ lookup('env', 'DB_USER') }} --dbpass={{ lookup('env', 'DB_PASS') }} --dbhost={{ lookup('env', 'DB_HOST') }}
    --extra-php="define( 'WP_DEBUG', true );
    define( 'WP_DEBUG_LOG', true );
    define('DISALLOW_FILE_EDIT',true);"
  args:
    chdir: "{{ lookup('env', 'STAGING_DIRECTORY') }}"
    creates: wp-config.php

- name: Install WordPress to stating environment
  command: "wp core install --url='{{staging_url}}' --title='{{staging_title}}' --admin_user='{{ lookup('env', 'STAGING_ADMIN_NAME') }}' --admin_password='{{ lookup('env', 'STAGING_ADMIN_PASS') }}' --admin_email='{{ lookup('env', 'STAGING_ADMIN_MAIL') }}'"
  args:
    chdir: "{{ lookup('env', 'STAGING_DIRECTORY') }}"

- name: Install common plugins to staging environment
  command: "wp plugin install {{ item }} --activate"
  args:
    chdir: "{{ lookup('env', 'STAGING_DIRECTORY') }}"
  with_items: "{{ common_plugins }}"

- name: Install staging plugins to staging environment
  command: "wp plugin install {{ item }} --activate"
  args:
    chdir: "{{ lookup('env', 'STAGING_DIRECTORY') }}"
  with_items: "{{ staging_plugins }}"

- name: Rewrite permalink structure
  command: "wp rewrite flush"
  args:
    chdir: "{{ lookup('env', 'STAGING_DIRECTORY') }}"
