- name: binフォルダを作成
  file:
    path: ~/bin
    state: directory

- name: wp-cliをインストールする
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: ~/bin/wp
    mode: "0755"

- name: wp-cliの情報をwp_info_resultに格納する
  command: "wp --info"
  register: wp_info_result

- name: wp-cliの情報を格納する
  debug:
    msg: "{{ wp_info_result }}"

- name: wp-cliのコンフィグファイルを格納するフォルダを作成
  file:
    path: ~/.wp-cli
    state: directory

- name: wp-cliのコンフィグファイルを作成（作るだけ）
  file:
    path: ~/.wp-cli/config.yml
    state: file
    mode: "755"
